### ISSUE TITLE
api/data base error

### ISSUE THREAD

**Issue by Dohv** [Dohv/project_3#6]
trying to see if the info from my database is on my localhost3001 and this is the error im getting from postman, the browser, and my terminal.

{
  "confirmation": "400",
  "err": {
    "code": "ECONNREFUSED",
    "errno": "ECONNREFUSED",
    "syscall": "connect",
    "address": "198.105.254.11",
    "port": 5432
  }
}

I have spoken to taka the new/old ta from turtles and we changed up the config file to have 
db = pgp('postgres://dovstokar@localhost:5432/tada');
.  

@thoughtbyte
@zfine416
@jlr7245

**Comment by jlr7245** [comment]
What does the error say in your console? It's probably at least a little bit more informative than the one in the browser
