### ISSUE TITLE
promise error

### ISSUE THREAD

**Issue by ahmedtsajib** [Dohv/project_3#9]
@jlr7245 
@thoughtbyte 
@shishkina 
@zfine416

Hi,  I'm getting the following error when trying to fetch data from weather api.

localhost/:1 Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0

I tried googling it and found this: https://github.com/sahat/megaboilerplate/issues/147

 but don't know if I should do this or there is another way to fix this.

Thanks

**Comment by jlr7245** [comment]
That one means that when you make the call you're making it incorrectly, and getting some kind of HTML response. Check your fetch request and make sure it's formatted properly, and that you have the proper keys if necessary. Try it out in postman etc.
